<?php

namespace Plugin\CategoryContent\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryContentRepository extends EntityRepository
{
}
